/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HqLoginRouteImport } from './routes/hq-login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HqRouteImport } from './routes/_hq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingIdRouteImport } from './routes/meeting.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as HqTrainingRouteImport } from './routes/_hq.training'
import { Route as HqTimeOffRouteImport } from './routes/_hq.time-off'
import { Route as HqTeamsRouteImport } from './routes/_hq.teams'
import { Route as HqTasksRouteImport } from './routes/_hq.tasks'
import { Route as HqSettingsRouteImport } from './routes/_hq.settings'
import { Route as HqSearchRouteImport } from './routes/_hq.search'
import { Route as HqReviewsRouteImport } from './routes/_hq.reviews'
import { Route as HqRequestsRouteImport } from './routes/_hq.requests'
import { Route as HqRdIdeasRouteImport } from './routes/_hq.rd-ideas'
import { Route as HqProfileRouteImport } from './routes/_hq.profile'
import { Route as HqPhoneRouteImport } from './routes/_hq.phone'
import { Route as HqOrgChartRouteImport } from './routes/_hq.org-chart'
import { Route as HqOnboardingRouteImport } from './routes/_hq.onboarding'
import { Route as HqNotificationsRouteImport } from './routes/_hq.notifications'
import { Route as HqMyTimeRouteImport } from './routes/_hq.my-time'
import { Route as HqMeetingsRouteImport } from './routes/_hq.meetings'
import { Route as HqMeetingNotesRouteImport } from './routes/_hq.meeting-notes'
import { Route as HqMailRouteImport } from './routes/_hq.mail'
import { Route as HqKbRouteImport } from './routes/_hq.kb'
import { Route as HqInvoicesRouteImport } from './routes/_hq.invoices'
import { Route as HqHiringRouteImport } from './routes/_hq.hiring'
import { Route as HqHelpRouteImport } from './routes/_hq.help'
import { Route as HqFinancialReportsRouteImport } from './routes/_hq.financial-reports'
import { Route as HqExpensesRouteImport } from './routes/_hq.expenses'
import { Route as HqEmployeesRouteImport } from './routes/_hq.employees'
import { Route as HqDriveRouteImport } from './routes/_hq.drive'
import { Route as HqDashboardRouteImport } from './routes/_hq.dashboard'
import { Route as HqCertificationsRouteImport } from './routes/_hq.certifications'
import { Route as HqCalendarRouteImport } from './routes/_hq.calendar'
import { Route as HqAttendanceRouteImport } from './routes/_hq.attendance'
import { Route as HqAnalyticsRouteImport } from './routes/_hq.analytics'
import { Route as HqAccountingRouteImport } from './routes/_hq.accounting'
import { Route as HqTeamsIndexRouteImport } from './routes/_hq.teams.index'
import { Route as HqTeamsSlugRouteImport } from './routes/_hq.teams.$slug'
import { Route as HqSystemsServicesRouteImport } from './routes/_hq.systems.services'
import { Route as HqSystemsHelpdeskRouteImport } from './routes/_hq.systems.helpdesk'
import { Route as HqSystemsAccessRouteImport } from './routes/_hq.systems.access'
import { Route as HqProductRoadmapRouteImport } from './routes/_hq.product.roadmap'
import { Route as HqProductReleasesRouteImport } from './routes/_hq.product.releases'
import { Route as HqProductFeedbackRouteImport } from './routes/_hq.product.feedback'
import { Route as HqOpsReadinessRouteImport } from './routes/_hq.ops.readiness'
import { Route as HqOpsFlightsRouteImport } from './routes/_hq.ops.flights'
import { Route as HqOpsDetectionsRouteImport } from './routes/_hq.ops.detections'
import { Route as HqOpsControlRouteImport } from './routes/_hq.ops.control'
import { Route as HqOpsAirspaceRouteImport } from './routes/_hq.ops.airspace'
import { Route as HqMfgSupplyRouteImport } from './routes/_hq.mfg.supply'
import { Route as HqMfgStockRouteImport } from './routes/_hq.mfg.stock'
import { Route as HqMfgQualityRouteImport } from './routes/_hq.mfg.quality'
import { Route as HqMfgLineRouteImport } from './routes/_hq.mfg.line'
import { Route as HqEngProgramsRouteImport } from './routes/_hq.eng.programs'
import { Route as HqEngIssuesRouteImport } from './routes/_hq.eng.issues'
import { Route as HqEngChangesRouteImport } from './routes/_hq.eng.changes'
import { Route as HqAdminSlackRouteImport } from './routes/_hq.admin.slack'
import { Route as HqAdminOrgRouteImport } from './routes/_hq.admin.org'
import { Route as HqAdminItRouteImport } from './routes/_hq.admin.it'
import { Route as HqAdminHealthRouteImport } from './routes/_hq.admin.health'
import { Route as HqAdminDepartmentsRouteImport } from './routes/_hq.admin.departments'
import { Route as HqAdminCompanyRouteImport } from './routes/_hq.admin.company'
import { Route as HqAdminAppsRouteImport } from './routes/_hq.admin.apps'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HqLoginRoute = HqLoginRouteImport.update({
  id: '/hq-login',
  path: '/hq-login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/_hq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIdRoute = MeetingIdRouteImport.update({
  id: '/meeting/$id',
  path: '/meeting/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const HqTrainingRoute = HqTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => HqRoute,
} as any)
const HqTimeOffRoute = HqTimeOffRouteImport.update({
  id: '/time-off',
  path: '/time-off',
  getParentRoute: () => HqRoute,
} as any)
const HqTeamsRoute = HqTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => HqRoute,
} as any)
const HqTasksRoute = HqTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => HqRoute,
} as any)
const HqSettingsRoute = HqSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HqRoute,
} as any)
const HqSearchRoute = HqSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HqRoute,
} as any)
const HqReviewsRoute = HqReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => HqRoute,
} as any)
const HqRequestsRoute = HqRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => HqRoute,
} as any)
const HqRdIdeasRoute = HqRdIdeasRouteImport.update({
  id: '/rd-ideas',
  path: '/rd-ideas',
  getParentRoute: () => HqRoute,
} as any)
const HqProfileRoute = HqProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HqRoute,
} as any)
const HqPhoneRoute = HqPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => HqRoute,
} as any)
const HqOrgChartRoute = HqOrgChartRouteImport.update({
  id: '/org-chart',
  path: '/org-chart',
  getParentRoute: () => HqRoute,
} as any)
const HqOnboardingRoute = HqOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => HqRoute,
} as any)
const HqNotificationsRoute = HqNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => HqRoute,
} as any)
const HqMyTimeRoute = HqMyTimeRouteImport.update({
  id: '/my-time',
  path: '/my-time',
  getParentRoute: () => HqRoute,
} as any)
const HqMeetingsRoute = HqMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => HqRoute,
} as any)
const HqMeetingNotesRoute = HqMeetingNotesRouteImport.update({
  id: '/meeting-notes',
  path: '/meeting-notes',
  getParentRoute: () => HqRoute,
} as any)
const HqMailRoute = HqMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => HqRoute,
} as any)
const HqKbRoute = HqKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => HqRoute,
} as any)
const HqInvoicesRoute = HqInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => HqRoute,
} as any)
const HqHiringRoute = HqHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => HqRoute,
} as any)
const HqHelpRoute = HqHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => HqRoute,
} as any)
const HqFinancialReportsRoute = HqFinancialReportsRouteImport.update({
  id: '/financial-reports',
  path: '/financial-reports',
  getParentRoute: () => HqRoute,
} as any)
const HqExpensesRoute = HqExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => HqRoute,
} as any)
const HqEmployeesRoute = HqEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => HqRoute,
} as any)
const HqDriveRoute = HqDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => HqRoute,
} as any)
const HqDashboardRoute = HqDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HqRoute,
} as any)
const HqCertificationsRoute = HqCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => HqRoute,
} as any)
const HqCalendarRoute = HqCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HqRoute,
} as any)
const HqAttendanceRoute = HqAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => HqRoute,
} as any)
const HqAnalyticsRoute = HqAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HqRoute,
} as any)
const HqAccountingRoute = HqAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => HqRoute,
} as any)
const HqTeamsIndexRoute = HqTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HqTeamsRoute,
} as any)
const HqTeamsSlugRoute = HqTeamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HqTeamsRoute,
} as any)
const HqSystemsServicesRoute = HqSystemsServicesRouteImport.update({
  id: '/systems/services',
  path: '/systems/services',
  getParentRoute: () => HqRoute,
} as any)
const HqSystemsHelpdeskRoute = HqSystemsHelpdeskRouteImport.update({
  id: '/systems/helpdesk',
  path: '/systems/helpdesk',
  getParentRoute: () => HqRoute,
} as any)
const HqSystemsAccessRoute = HqSystemsAccessRouteImport.update({
  id: '/systems/access',
  path: '/systems/access',
  getParentRoute: () => HqRoute,
} as any)
const HqProductRoadmapRoute = HqProductRoadmapRouteImport.update({
  id: '/product/roadmap',
  path: '/product/roadmap',
  getParentRoute: () => HqRoute,
} as any)
const HqProductReleasesRoute = HqProductReleasesRouteImport.update({
  id: '/product/releases',
  path: '/product/releases',
  getParentRoute: () => HqRoute,
} as any)
const HqProductFeedbackRoute = HqProductFeedbackRouteImport.update({
  id: '/product/feedback',
  path: '/product/feedback',
  getParentRoute: () => HqRoute,
} as any)
const HqOpsReadinessRoute = HqOpsReadinessRouteImport.update({
  id: '/ops/readiness',
  path: '/ops/readiness',
  getParentRoute: () => HqRoute,
} as any)
const HqOpsFlightsRoute = HqOpsFlightsRouteImport.update({
  id: '/ops/flights',
  path: '/ops/flights',
  getParentRoute: () => HqRoute,
} as any)
const HqOpsDetectionsRoute = HqOpsDetectionsRouteImport.update({
  id: '/ops/detections',
  path: '/ops/detections',
  getParentRoute: () => HqRoute,
} as any)
const HqOpsControlRoute = HqOpsControlRouteImport.update({
  id: '/ops/control',
  path: '/ops/control',
  getParentRoute: () => HqRoute,
} as any)
const HqOpsAirspaceRoute = HqOpsAirspaceRouteImport.update({
  id: '/ops/airspace',
  path: '/ops/airspace',
  getParentRoute: () => HqRoute,
} as any)
const HqMfgSupplyRoute = HqMfgSupplyRouteImport.update({
  id: '/mfg/supply',
  path: '/mfg/supply',
  getParentRoute: () => HqRoute,
} as any)
const HqMfgStockRoute = HqMfgStockRouteImport.update({
  id: '/mfg/stock',
  path: '/mfg/stock',
  getParentRoute: () => HqRoute,
} as any)
const HqMfgQualityRoute = HqMfgQualityRouteImport.update({
  id: '/mfg/quality',
  path: '/mfg/quality',
  getParentRoute: () => HqRoute,
} as any)
const HqMfgLineRoute = HqMfgLineRouteImport.update({
  id: '/mfg/line',
  path: '/mfg/line',
  getParentRoute: () => HqRoute,
} as any)
const HqEngProgramsRoute = HqEngProgramsRouteImport.update({
  id: '/eng/programs',
  path: '/eng/programs',
  getParentRoute: () => HqRoute,
} as any)
const HqEngIssuesRoute = HqEngIssuesRouteImport.update({
  id: '/eng/issues',
  path: '/eng/issues',
  getParentRoute: () => HqRoute,
} as any)
const HqEngChangesRoute = HqEngChangesRouteImport.update({
  id: '/eng/changes',
  path: '/eng/changes',
  getParentRoute: () => HqRoute,
} as any)
const HqAdminSlackRoute = HqAdminSlackRouteImport.update({
  id: '/admin/slack',
  path: '/admin/slack',
  getParentRoute: () => HqRoute,
} as any)
const HqAdminOrgRoute = HqAdminOrgRouteImport.update({
  id: '/admin/org',
  path: '/admin/org',
  getParentRoute: () => HqRoute,
} as any)
const HqAdminItRoute = HqAdminItRouteImport.update({
  id: '/admin/it',
  path: '/admin/it',
  getParentRoute: () => HqRoute,
} as any)
const HqAdminHealthRoute = HqAdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => HqRoute,
} as any)
const HqAdminDepartmentsRoute = HqAdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => HqRoute,
} as any)
const HqAdminCompanyRoute = HqAdminCompanyRouteImport.update({
  id: '/admin/company',
  path: '/admin/company',
  getParentRoute: () => HqRoute,
} as any)
const HqAdminAppsRoute = HqAdminAppsRouteImport.update({
  id: '/admin/apps',
  path: '/admin/apps',
  getParentRoute: () => HqRoute,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/hq-login': typeof HqLoginRoute
  '/join': typeof JoinRoute
  '/mission': typeof MissionRoute
  '/operations': typeof OperationsRoute
  '/partners': typeof PartnersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system': typeof SystemRoute
  '/technology': typeof TechnologyRoute
  '/welcome': typeof WelcomeRoute
  '/workspaces': typeof WorkspacesRoute
  '/accounting': typeof HqAccountingRoute
  '/analytics': typeof HqAnalyticsRoute
  '/attendance': typeof HqAttendanceRoute
  '/calendar': typeof HqCalendarRoute
  '/certifications': typeof HqCertificationsRoute
  '/dashboard': typeof HqDashboardRoute
  '/drive': typeof HqDriveRoute
  '/employees': typeof HqEmployeesRoute
  '/expenses': typeof HqExpensesRoute
  '/financial-reports': typeof HqFinancialReportsRoute
  '/help': typeof HqHelpRoute
  '/hiring': typeof HqHiringRoute
  '/invoices': typeof HqInvoicesRoute
  '/kb': typeof HqKbRoute
  '/mail': typeof HqMailRoute
  '/meeting-notes': typeof HqMeetingNotesRoute
  '/meetings': typeof HqMeetingsRoute
  '/my-time': typeof HqMyTimeRoute
  '/notifications': typeof HqNotificationsRoute
  '/onboarding': typeof HqOnboardingRoute
  '/org-chart': typeof HqOrgChartRoute
  '/phone': typeof HqPhoneRoute
  '/profile': typeof HqProfileRoute
  '/rd-ideas': typeof HqRdIdeasRoute
  '/requests': typeof HqRequestsRoute
  '/reviews': typeof HqReviewsRoute
  '/search': typeof HqSearchRoute
  '/settings': typeof HqSettingsRoute
  '/tasks': typeof HqTasksRoute
  '/teams': typeof HqTeamsRouteWithChildren
  '/time-off': typeof HqTimeOffRoute
  '/training': typeof HqTrainingRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/admin/apps': typeof HqAdminAppsRoute
  '/admin/company': typeof HqAdminCompanyRoute
  '/admin/departments': typeof HqAdminDepartmentsRoute
  '/admin/health': typeof HqAdminHealthRoute
  '/admin/it': typeof HqAdminItRoute
  '/admin/org': typeof HqAdminOrgRoute
  '/admin/slack': typeof HqAdminSlackRoute
  '/eng/changes': typeof HqEngChangesRoute
  '/eng/issues': typeof HqEngIssuesRoute
  '/eng/programs': typeof HqEngProgramsRoute
  '/mfg/line': typeof HqMfgLineRoute
  '/mfg/quality': typeof HqMfgQualityRoute
  '/mfg/stock': typeof HqMfgStockRoute
  '/mfg/supply': typeof HqMfgSupplyRoute
  '/ops/airspace': typeof HqOpsAirspaceRoute
  '/ops/control': typeof HqOpsControlRoute
  '/ops/detections': typeof HqOpsDetectionsRoute
  '/ops/flights': typeof HqOpsFlightsRoute
  '/ops/readiness': typeof HqOpsReadinessRoute
  '/product/feedback': typeof HqProductFeedbackRoute
  '/product/releases': typeof HqProductReleasesRoute
  '/product/roadmap': typeof HqProductRoadmapRoute
  '/systems/access': typeof HqSystemsAccessRoute
  '/systems/helpdesk': typeof HqSystemsHelpdeskRoute
  '/systems/services': typeof HqSystemsServicesRoute
  '/teams/$slug': typeof HqTeamsSlugRoute
  '/teams/': typeof HqTeamsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/hq-login': typeof HqLoginRoute
  '/join': typeof JoinRoute
  '/mission': typeof MissionRoute
  '/operations': typeof OperationsRoute
  '/partners': typeof PartnersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system': typeof SystemRoute
  '/technology': typeof TechnologyRoute
  '/welcome': typeof WelcomeRoute
  '/workspaces': typeof WorkspacesRoute
  '/accounting': typeof HqAccountingRoute
  '/analytics': typeof HqAnalyticsRoute
  '/attendance': typeof HqAttendanceRoute
  '/calendar': typeof HqCalendarRoute
  '/certifications': typeof HqCertificationsRoute
  '/dashboard': typeof HqDashboardRoute
  '/drive': typeof HqDriveRoute
  '/employees': typeof HqEmployeesRoute
  '/expenses': typeof HqExpensesRoute
  '/financial-reports': typeof HqFinancialReportsRoute
  '/help': typeof HqHelpRoute
  '/hiring': typeof HqHiringRoute
  '/invoices': typeof HqInvoicesRoute
  '/kb': typeof HqKbRoute
  '/mail': typeof HqMailRoute
  '/meeting-notes': typeof HqMeetingNotesRoute
  '/meetings': typeof HqMeetingsRoute
  '/my-time': typeof HqMyTimeRoute
  '/notifications': typeof HqNotificationsRoute
  '/onboarding': typeof HqOnboardingRoute
  '/org-chart': typeof HqOrgChartRoute
  '/phone': typeof HqPhoneRoute
  '/profile': typeof HqProfileRoute
  '/rd-ideas': typeof HqRdIdeasRoute
  '/requests': typeof HqRequestsRoute
  '/reviews': typeof HqReviewsRoute
  '/search': typeof HqSearchRoute
  '/settings': typeof HqSettingsRoute
  '/tasks': typeof HqTasksRoute
  '/time-off': typeof HqTimeOffRoute
  '/training': typeof HqTrainingRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/admin/apps': typeof HqAdminAppsRoute
  '/admin/company': typeof HqAdminCompanyRoute
  '/admin/departments': typeof HqAdminDepartmentsRoute
  '/admin/health': typeof HqAdminHealthRoute
  '/admin/it': typeof HqAdminItRoute
  '/admin/org': typeof HqAdminOrgRoute
  '/admin/slack': typeof HqAdminSlackRoute
  '/eng/changes': typeof HqEngChangesRoute
  '/eng/issues': typeof HqEngIssuesRoute
  '/eng/programs': typeof HqEngProgramsRoute
  '/mfg/line': typeof HqMfgLineRoute
  '/mfg/quality': typeof HqMfgQualityRoute
  '/mfg/stock': typeof HqMfgStockRoute
  '/mfg/supply': typeof HqMfgSupplyRoute
  '/ops/airspace': typeof HqOpsAirspaceRoute
  '/ops/control': typeof HqOpsControlRoute
  '/ops/detections': typeof HqOpsDetectionsRoute
  '/ops/flights': typeof HqOpsFlightsRoute
  '/ops/readiness': typeof HqOpsReadinessRoute
  '/product/feedback': typeof HqProductFeedbackRoute
  '/product/releases': typeof HqProductReleasesRoute
  '/product/roadmap': typeof HqProductRoadmapRoute
  '/systems/access': typeof HqSystemsAccessRoute
  '/systems/helpdesk': typeof HqSystemsHelpdeskRoute
  '/systems/services': typeof HqSystemsServicesRoute
  '/teams/$slug': typeof HqTeamsSlugRoute
  '/teams': typeof HqTeamsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_hq': typeof HqRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/hq-login': typeof HqLoginRoute
  '/join': typeof JoinRoute
  '/mission': typeof MissionRoute
  '/operations': typeof OperationsRoute
  '/partners': typeof PartnersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system': typeof SystemRoute
  '/technology': typeof TechnologyRoute
  '/welcome': typeof WelcomeRoute
  '/workspaces': typeof WorkspacesRoute
  '/_hq/accounting': typeof HqAccountingRoute
  '/_hq/analytics': typeof HqAnalyticsRoute
  '/_hq/attendance': typeof HqAttendanceRoute
  '/_hq/calendar': typeof HqCalendarRoute
  '/_hq/certifications': typeof HqCertificationsRoute
  '/_hq/dashboard': typeof HqDashboardRoute
  '/_hq/drive': typeof HqDriveRoute
  '/_hq/employees': typeof HqEmployeesRoute
  '/_hq/expenses': typeof HqExpensesRoute
  '/_hq/financial-reports': typeof HqFinancialReportsRoute
  '/_hq/help': typeof HqHelpRoute
  '/_hq/hiring': typeof HqHiringRoute
  '/_hq/invoices': typeof HqInvoicesRoute
  '/_hq/kb': typeof HqKbRoute
  '/_hq/mail': typeof HqMailRoute
  '/_hq/meeting-notes': typeof HqMeetingNotesRoute
  '/_hq/meetings': typeof HqMeetingsRoute
  '/_hq/my-time': typeof HqMyTimeRoute
  '/_hq/notifications': typeof HqNotificationsRoute
  '/_hq/onboarding': typeof HqOnboardingRoute
  '/_hq/org-chart': typeof HqOrgChartRoute
  '/_hq/phone': typeof HqPhoneRoute
  '/_hq/profile': typeof HqProfileRoute
  '/_hq/rd-ideas': typeof HqRdIdeasRoute
  '/_hq/requests': typeof HqRequestsRoute
  '/_hq/reviews': typeof HqReviewsRoute
  '/_hq/search': typeof HqSearchRoute
  '/_hq/settings': typeof HqSettingsRoute
  '/_hq/tasks': typeof HqTasksRoute
  '/_hq/teams': typeof HqTeamsRouteWithChildren
  '/_hq/time-off': typeof HqTimeOffRoute
  '/_hq/training': typeof HqTrainingRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/_hq/admin/apps': typeof HqAdminAppsRoute
  '/_hq/admin/company': typeof HqAdminCompanyRoute
  '/_hq/admin/departments': typeof HqAdminDepartmentsRoute
  '/_hq/admin/health': typeof HqAdminHealthRoute
  '/_hq/admin/it': typeof HqAdminItRoute
  '/_hq/admin/org': typeof HqAdminOrgRoute
  '/_hq/admin/slack': typeof HqAdminSlackRoute
  '/_hq/eng/changes': typeof HqEngChangesRoute
  '/_hq/eng/issues': typeof HqEngIssuesRoute
  '/_hq/eng/programs': typeof HqEngProgramsRoute
  '/_hq/mfg/line': typeof HqMfgLineRoute
  '/_hq/mfg/quality': typeof HqMfgQualityRoute
  '/_hq/mfg/stock': typeof HqMfgStockRoute
  '/_hq/mfg/supply': typeof HqMfgSupplyRoute
  '/_hq/ops/airspace': typeof HqOpsAirspaceRoute
  '/_hq/ops/control': typeof HqOpsControlRoute
  '/_hq/ops/detections': typeof HqOpsDetectionsRoute
  '/_hq/ops/flights': typeof HqOpsFlightsRoute
  '/_hq/ops/readiness': typeof HqOpsReadinessRoute
  '/_hq/product/feedback': typeof HqProductFeedbackRoute
  '/_hq/product/releases': typeof HqProductReleasesRoute
  '/_hq/product/roadmap': typeof HqProductRoadmapRoute
  '/_hq/systems/access': typeof HqSystemsAccessRoute
  '/_hq/systems/helpdesk': typeof HqSystemsHelpdeskRoute
  '/_hq/systems/services': typeof HqSystemsServicesRoute
  '/_hq/teams/$slug': typeof HqTeamsSlugRoute
  '/_hq/teams/': typeof HqTeamsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/development'
    | '/donate'
    | '/faq'
    | '/hq-login'
    | '/join'
    | '/mission'
    | '/operations'
    | '/partners'
    | '/sitemap.xml'
    | '/system'
    | '/technology'
    | '/welcome'
    | '/workspaces'
    | '/accounting'
    | '/analytics'
    | '/attendance'
    | '/calendar'
    | '/certifications'
    | '/dashboard'
    | '/drive'
    | '/employees'
    | '/expenses'
    | '/financial-reports'
    | '/help'
    | '/hiring'
    | '/invoices'
    | '/kb'
    | '/mail'
    | '/meeting-notes'
    | '/meetings'
    | '/my-time'
    | '/notifications'
    | '/onboarding'
    | '/org-chart'
    | '/phone'
    | '/profile'
    | '/rd-ideas'
    | '/requests'
    | '/reviews'
    | '/search'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/time-off'
    | '/training'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/meeting/$id'
    | '/admin/apps'
    | '/admin/company'
    | '/admin/departments'
    | '/admin/health'
    | '/admin/it'
    | '/admin/org'
    | '/admin/slack'
    | '/eng/changes'
    | '/eng/issues'
    | '/eng/programs'
    | '/mfg/line'
    | '/mfg/quality'
    | '/mfg/stock'
    | '/mfg/supply'
    | '/ops/airspace'
    | '/ops/control'
    | '/ops/detections'
    | '/ops/flights'
    | '/ops/readiness'
    | '/product/feedback'
    | '/product/releases'
    | '/product/roadmap'
    | '/systems/access'
    | '/systems/helpdesk'
    | '/systems/services'
    | '/teams/$slug'
    | '/teams/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/development'
    | '/donate'
    | '/faq'
    | '/hq-login'
    | '/join'
    | '/mission'
    | '/operations'
    | '/partners'
    | '/sitemap.xml'
    | '/system'
    | '/technology'
    | '/welcome'
    | '/workspaces'
    | '/accounting'
    | '/analytics'
    | '/attendance'
    | '/calendar'
    | '/certifications'
    | '/dashboard'
    | '/drive'
    | '/employees'
    | '/expenses'
    | '/financial-reports'
    | '/help'
    | '/hiring'
    | '/invoices'
    | '/kb'
    | '/mail'
    | '/meeting-notes'
    | '/meetings'
    | '/my-time'
    | '/notifications'
    | '/onboarding'
    | '/org-chart'
    | '/phone'
    | '/profile'
    | '/rd-ideas'
    | '/requests'
    | '/reviews'
    | '/search'
    | '/settings'
    | '/tasks'
    | '/time-off'
    | '/training'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/meeting/$id'
    | '/admin/apps'
    | '/admin/company'
    | '/admin/departments'
    | '/admin/health'
    | '/admin/it'
    | '/admin/org'
    | '/admin/slack'
    | '/eng/changes'
    | '/eng/issues'
    | '/eng/programs'
    | '/mfg/line'
    | '/mfg/quality'
    | '/mfg/stock'
    | '/mfg/supply'
    | '/ops/airspace'
    | '/ops/control'
    | '/ops/detections'
    | '/ops/flights'
    | '/ops/readiness'
    | '/product/feedback'
    | '/product/releases'
    | '/product/roadmap'
    | '/systems/access'
    | '/systems/helpdesk'
    | '/systems/services'
    | '/teams/$slug'
    | '/teams'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_hq'
    | '/about'
    | '/contact'
    | '/development'
    | '/donate'
    | '/faq'
    | '/hq-login'
    | '/join'
    | '/mission'
    | '/operations'
    | '/partners'
    | '/sitemap.xml'
    | '/system'
    | '/technology'
    | '/welcome'
    | '/workspaces'
    | '/_hq/accounting'
    | '/_hq/analytics'
    | '/_hq/attendance'
    | '/_hq/calendar'
    | '/_hq/certifications'
    | '/_hq/dashboard'
    | '/_hq/drive'
    | '/_hq/employees'
    | '/_hq/expenses'
    | '/_hq/financial-reports'
    | '/_hq/help'
    | '/_hq/hiring'
    | '/_hq/invoices'
    | '/_hq/kb'
    | '/_hq/mail'
    | '/_hq/meeting-notes'
    | '/_hq/meetings'
    | '/_hq/my-time'
    | '/_hq/notifications'
    | '/_hq/onboarding'
    | '/_hq/org-chart'
    | '/_hq/phone'
    | '/_hq/profile'
    | '/_hq/rd-ideas'
    | '/_hq/requests'
    | '/_hq/reviews'
    | '/_hq/search'
    | '/_hq/settings'
    | '/_hq/tasks'
    | '/_hq/teams'
    | '/_hq/time-off'
    | '/_hq/training'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/meeting/$id'
    | '/_hq/admin/apps'
    | '/_hq/admin/company'
    | '/_hq/admin/departments'
    | '/_hq/admin/health'
    | '/_hq/admin/it'
    | '/_hq/admin/org'
    | '/_hq/admin/slack'
    | '/_hq/eng/changes'
    | '/_hq/eng/issues'
    | '/_hq/eng/programs'
    | '/_hq/mfg/line'
    | '/_hq/mfg/quality'
    | '/_hq/mfg/stock'
    | '/_hq/mfg/supply'
    | '/_hq/ops/airspace'
    | '/_hq/ops/control'
    | '/_hq/ops/detections'
    | '/_hq/ops/flights'
    | '/_hq/ops/readiness'
    | '/_hq/product/feedback'
    | '/_hq/product/releases'
    | '/_hq/product/roadmap'
    | '/_hq/systems/access'
    | '/_hq/systems/helpdesk'
    | '/_hq/systems/services'
    | '/_hq/teams/$slug'
    | '/_hq/teams/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HqRoute: typeof HqRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DevelopmentRoute: typeof DevelopmentRoute
  DonateRoute: typeof DonateRoute
  FaqRoute: typeof FaqRoute
  HqLoginRoute: typeof HqLoginRoute
  JoinRoute: typeof JoinRoute
  MissionRoute: typeof MissionRoute
  OperationsRoute: typeof OperationsRoute
  PartnersRoute: typeof PartnersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SystemRoute: typeof SystemRoute
  TechnologyRoute: typeof TechnologyRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkspacesRoute: typeof WorkspacesRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MeetingIdRoute: typeof MeetingIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq-login': {
      id: '/hq-login'
      path: '/hq-login'
      fullPath: '/hq-login'
      preLoaderRoute: typeof HqLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hq': {
      id: '/_hq'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$id': {
      id: '/meeting/$id'
      path: '/meeting/$id'
      fullPath: '/meeting/$id'
      preLoaderRoute: typeof MeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hq/training': {
      id: '/_hq/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof HqTrainingRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/time-off': {
      id: '/_hq/time-off'
      path: '/time-off'
      fullPath: '/time-off'
      preLoaderRoute: typeof HqTimeOffRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/teams': {
      id: '/_hq/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof HqTeamsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/tasks': {
      id: '/_hq/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof HqTasksRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/settings': {
      id: '/_hq/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof HqSettingsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/search': {
      id: '/_hq/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof HqSearchRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/reviews': {
      id: '/_hq/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof HqReviewsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/requests': {
      id: '/_hq/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof HqRequestsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/rd-ideas': {
      id: '/_hq/rd-ideas'
      path: '/rd-ideas'
      fullPath: '/rd-ideas'
      preLoaderRoute: typeof HqRdIdeasRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/profile': {
      id: '/_hq/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HqProfileRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/phone': {
      id: '/_hq/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof HqPhoneRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/org-chart': {
      id: '/_hq/org-chart'
      path: '/org-chart'
      fullPath: '/org-chart'
      preLoaderRoute: typeof HqOrgChartRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/onboarding': {
      id: '/_hq/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof HqOnboardingRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/notifications': {
      id: '/_hq/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof HqNotificationsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/my-time': {
      id: '/_hq/my-time'
      path: '/my-time'
      fullPath: '/my-time'
      preLoaderRoute: typeof HqMyTimeRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/meetings': {
      id: '/_hq/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof HqMeetingsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/meeting-notes': {
      id: '/_hq/meeting-notes'
      path: '/meeting-notes'
      fullPath: '/meeting-notes'
      preLoaderRoute: typeof HqMeetingNotesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/mail': {
      id: '/_hq/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof HqMailRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/kb': {
      id: '/_hq/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof HqKbRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/invoices': {
      id: '/_hq/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof HqInvoicesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/hiring': {
      id: '/_hq/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HqHiringRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/help': {
      id: '/_hq/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HqHelpRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/financial-reports': {
      id: '/_hq/financial-reports'
      path: '/financial-reports'
      fullPath: '/financial-reports'
      preLoaderRoute: typeof HqFinancialReportsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/expenses': {
      id: '/_hq/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof HqExpensesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/employees': {
      id: '/_hq/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof HqEmployeesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/drive': {
      id: '/_hq/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof HqDriveRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/dashboard': {
      id: '/_hq/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HqDashboardRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/certifications': {
      id: '/_hq/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof HqCertificationsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/calendar': {
      id: '/_hq/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof HqCalendarRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/attendance': {
      id: '/_hq/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof HqAttendanceRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/analytics': {
      id: '/_hq/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof HqAnalyticsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/accounting': {
      id: '/_hq/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof HqAccountingRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/teams/': {
      id: '/_hq/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof HqTeamsIndexRouteImport
      parentRoute: typeof HqTeamsRoute
    }
    '/_hq/teams/$slug': {
      id: '/_hq/teams/$slug'
      path: '/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof HqTeamsSlugRouteImport
      parentRoute: typeof HqTeamsRoute
    }
    '/_hq/systems/services': {
      id: '/_hq/systems/services'
      path: '/systems/services'
      fullPath: '/systems/services'
      preLoaderRoute: typeof HqSystemsServicesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/systems/helpdesk': {
      id: '/_hq/systems/helpdesk'
      path: '/systems/helpdesk'
      fullPath: '/systems/helpdesk'
      preLoaderRoute: typeof HqSystemsHelpdeskRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/systems/access': {
      id: '/_hq/systems/access'
      path: '/systems/access'
      fullPath: '/systems/access'
      preLoaderRoute: typeof HqSystemsAccessRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/product/roadmap': {
      id: '/_hq/product/roadmap'
      path: '/product/roadmap'
      fullPath: '/product/roadmap'
      preLoaderRoute: typeof HqProductRoadmapRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/product/releases': {
      id: '/_hq/product/releases'
      path: '/product/releases'
      fullPath: '/product/releases'
      preLoaderRoute: typeof HqProductReleasesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/product/feedback': {
      id: '/_hq/product/feedback'
      path: '/product/feedback'
      fullPath: '/product/feedback'
      preLoaderRoute: typeof HqProductFeedbackRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/ops/readiness': {
      id: '/_hq/ops/readiness'
      path: '/ops/readiness'
      fullPath: '/ops/readiness'
      preLoaderRoute: typeof HqOpsReadinessRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/ops/flights': {
      id: '/_hq/ops/flights'
      path: '/ops/flights'
      fullPath: '/ops/flights'
      preLoaderRoute: typeof HqOpsFlightsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/ops/detections': {
      id: '/_hq/ops/detections'
      path: '/ops/detections'
      fullPath: '/ops/detections'
      preLoaderRoute: typeof HqOpsDetectionsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/ops/control': {
      id: '/_hq/ops/control'
      path: '/ops/control'
      fullPath: '/ops/control'
      preLoaderRoute: typeof HqOpsControlRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/ops/airspace': {
      id: '/_hq/ops/airspace'
      path: '/ops/airspace'
      fullPath: '/ops/airspace'
      preLoaderRoute: typeof HqOpsAirspaceRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/mfg/supply': {
      id: '/_hq/mfg/supply'
      path: '/mfg/supply'
      fullPath: '/mfg/supply'
      preLoaderRoute: typeof HqMfgSupplyRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/mfg/stock': {
      id: '/_hq/mfg/stock'
      path: '/mfg/stock'
      fullPath: '/mfg/stock'
      preLoaderRoute: typeof HqMfgStockRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/mfg/quality': {
      id: '/_hq/mfg/quality'
      path: '/mfg/quality'
      fullPath: '/mfg/quality'
      preLoaderRoute: typeof HqMfgQualityRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/mfg/line': {
      id: '/_hq/mfg/line'
      path: '/mfg/line'
      fullPath: '/mfg/line'
      preLoaderRoute: typeof HqMfgLineRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/eng/programs': {
      id: '/_hq/eng/programs'
      path: '/eng/programs'
      fullPath: '/eng/programs'
      preLoaderRoute: typeof HqEngProgramsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/eng/issues': {
      id: '/_hq/eng/issues'
      path: '/eng/issues'
      fullPath: '/eng/issues'
      preLoaderRoute: typeof HqEngIssuesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/eng/changes': {
      id: '/_hq/eng/changes'
      path: '/eng/changes'
      fullPath: '/eng/changes'
      preLoaderRoute: typeof HqEngChangesRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/admin/slack': {
      id: '/_hq/admin/slack'
      path: '/admin/slack'
      fullPath: '/admin/slack'
      preLoaderRoute: typeof HqAdminSlackRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/admin/org': {
      id: '/_hq/admin/org'
      path: '/admin/org'
      fullPath: '/admin/org'
      preLoaderRoute: typeof HqAdminOrgRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/admin/it': {
      id: '/_hq/admin/it'
      path: '/admin/it'
      fullPath: '/admin/it'
      preLoaderRoute: typeof HqAdminItRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/admin/health': {
      id: '/_hq/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof HqAdminHealthRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/admin/departments': {
      id: '/_hq/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof HqAdminDepartmentsRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/admin/company': {
      id: '/_hq/admin/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof HqAdminCompanyRouteImport
      parentRoute: typeof HqRoute
    }
    '/_hq/admin/apps': {
      id: '/_hq/admin/apps'
      path: '/admin/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof HqAdminAppsRouteImport
      parentRoute: typeof HqRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HqTeamsRouteChildren {
  HqTeamsSlugRoute: typeof HqTeamsSlugRoute
  HqTeamsIndexRoute: typeof HqTeamsIndexRoute
}

const HqTeamsRouteChildren: HqTeamsRouteChildren = {
  HqTeamsSlugRoute: HqTeamsSlugRoute,
  HqTeamsIndexRoute: HqTeamsIndexRoute,
}

const HqTeamsRouteWithChildren =
  HqTeamsRoute._addFileChildren(HqTeamsRouteChildren)

interface HqRouteChildren {
  HqAccountingRoute: typeof HqAccountingRoute
  HqAnalyticsRoute: typeof HqAnalyticsRoute
  HqAttendanceRoute: typeof HqAttendanceRoute
  HqCalendarRoute: typeof HqCalendarRoute
  HqCertificationsRoute: typeof HqCertificationsRoute
  HqDashboardRoute: typeof HqDashboardRoute
  HqDriveRoute: typeof HqDriveRoute
  HqEmployeesRoute: typeof HqEmployeesRoute
  HqExpensesRoute: typeof HqExpensesRoute
  HqFinancialReportsRoute: typeof HqFinancialReportsRoute
  HqHelpRoute: typeof HqHelpRoute
  HqHiringRoute: typeof HqHiringRoute
  HqInvoicesRoute: typeof HqInvoicesRoute
  HqKbRoute: typeof HqKbRoute
  HqMailRoute: typeof HqMailRoute
  HqMeetingNotesRoute: typeof HqMeetingNotesRoute
  HqMeetingsRoute: typeof HqMeetingsRoute
  HqMyTimeRoute: typeof HqMyTimeRoute
  HqNotificationsRoute: typeof HqNotificationsRoute
  HqOnboardingRoute: typeof HqOnboardingRoute
  HqOrgChartRoute: typeof HqOrgChartRoute
  HqPhoneRoute: typeof HqPhoneRoute
  HqProfileRoute: typeof HqProfileRoute
  HqRdIdeasRoute: typeof HqRdIdeasRoute
  HqRequestsRoute: typeof HqRequestsRoute
  HqReviewsRoute: typeof HqReviewsRoute
  HqSearchRoute: typeof HqSearchRoute
  HqSettingsRoute: typeof HqSettingsRoute
  HqTasksRoute: typeof HqTasksRoute
  HqTeamsRoute: typeof HqTeamsRouteWithChildren
  HqTimeOffRoute: typeof HqTimeOffRoute
  HqTrainingRoute: typeof HqTrainingRoute
  HqAdminAppsRoute: typeof HqAdminAppsRoute
  HqAdminCompanyRoute: typeof HqAdminCompanyRoute
  HqAdminDepartmentsRoute: typeof HqAdminDepartmentsRoute
  HqAdminHealthRoute: typeof HqAdminHealthRoute
  HqAdminItRoute: typeof HqAdminItRoute
  HqAdminOrgRoute: typeof HqAdminOrgRoute
  HqAdminSlackRoute: typeof HqAdminSlackRoute
  HqEngChangesRoute: typeof HqEngChangesRoute
  HqEngIssuesRoute: typeof HqEngIssuesRoute
  HqEngProgramsRoute: typeof HqEngProgramsRoute
  HqMfgLineRoute: typeof HqMfgLineRoute
  HqMfgQualityRoute: typeof HqMfgQualityRoute
  HqMfgStockRoute: typeof HqMfgStockRoute
  HqMfgSupplyRoute: typeof HqMfgSupplyRoute
  HqOpsAirspaceRoute: typeof HqOpsAirspaceRoute
  HqOpsControlRoute: typeof HqOpsControlRoute
  HqOpsDetectionsRoute: typeof HqOpsDetectionsRoute
  HqOpsFlightsRoute: typeof HqOpsFlightsRoute
  HqOpsReadinessRoute: typeof HqOpsReadinessRoute
  HqProductFeedbackRoute: typeof HqProductFeedbackRoute
  HqProductReleasesRoute: typeof HqProductReleasesRoute
  HqProductRoadmapRoute: typeof HqProductRoadmapRoute
  HqSystemsAccessRoute: typeof HqSystemsAccessRoute
  HqSystemsHelpdeskRoute: typeof HqSystemsHelpdeskRoute
  HqSystemsServicesRoute: typeof HqSystemsServicesRoute
}

const HqRouteChildren: HqRouteChildren = {
  HqAccountingRoute: HqAccountingRoute,
  HqAnalyticsRoute: HqAnalyticsRoute,
  HqAttendanceRoute: HqAttendanceRoute,
  HqCalendarRoute: HqCalendarRoute,
  HqCertificationsRoute: HqCertificationsRoute,
  HqDashboardRoute: HqDashboardRoute,
  HqDriveRoute: HqDriveRoute,
  HqEmployeesRoute: HqEmployeesRoute,
  HqExpensesRoute: HqExpensesRoute,
  HqFinancialReportsRoute: HqFinancialReportsRoute,
  HqHelpRoute: HqHelpRoute,
  HqHiringRoute: HqHiringRoute,
  HqInvoicesRoute: HqInvoicesRoute,
  HqKbRoute: HqKbRoute,
  HqMailRoute: HqMailRoute,
  HqMeetingNotesRoute: HqMeetingNotesRoute,
  HqMeetingsRoute: HqMeetingsRoute,
  HqMyTimeRoute: HqMyTimeRoute,
  HqNotificationsRoute: HqNotificationsRoute,
  HqOnboardingRoute: HqOnboardingRoute,
  HqOrgChartRoute: HqOrgChartRoute,
  HqPhoneRoute: HqPhoneRoute,
  HqProfileRoute: HqProfileRoute,
  HqRdIdeasRoute: HqRdIdeasRoute,
  HqRequestsRoute: HqRequestsRoute,
  HqReviewsRoute: HqReviewsRoute,
  HqSearchRoute: HqSearchRoute,
  HqSettingsRoute: HqSettingsRoute,
  HqTasksRoute: HqTasksRoute,
  HqTeamsRoute: HqTeamsRouteWithChildren,
  HqTimeOffRoute: HqTimeOffRoute,
  HqTrainingRoute: HqTrainingRoute,
  HqAdminAppsRoute: HqAdminAppsRoute,
  HqAdminCompanyRoute: HqAdminCompanyRoute,
  HqAdminDepartmentsRoute: HqAdminDepartmentsRoute,
  HqAdminHealthRoute: HqAdminHealthRoute,
  HqAdminItRoute: HqAdminItRoute,
  HqAdminOrgRoute: HqAdminOrgRoute,
  HqAdminSlackRoute: HqAdminSlackRoute,
  HqEngChangesRoute: HqEngChangesRoute,
  HqEngIssuesRoute: HqEngIssuesRoute,
  HqEngProgramsRoute: HqEngProgramsRoute,
  HqMfgLineRoute: HqMfgLineRoute,
  HqMfgQualityRoute: HqMfgQualityRoute,
  HqMfgStockRoute: HqMfgStockRoute,
  HqMfgSupplyRoute: HqMfgSupplyRoute,
  HqOpsAirspaceRoute: HqOpsAirspaceRoute,
  HqOpsControlRoute: HqOpsControlRoute,
  HqOpsDetectionsRoute: HqOpsDetectionsRoute,
  HqOpsFlightsRoute: HqOpsFlightsRoute,
  HqOpsReadinessRoute: HqOpsReadinessRoute,
  HqProductFeedbackRoute: HqProductFeedbackRoute,
  HqProductReleasesRoute: HqProductReleasesRoute,
  HqProductRoadmapRoute: HqProductRoadmapRoute,
  HqSystemsAccessRoute: HqSystemsAccessRoute,
  HqSystemsHelpdeskRoute: HqSystemsHelpdeskRoute,
  HqSystemsServicesRoute: HqSystemsServicesRoute,
}

const HqRouteWithChildren = HqRoute._addFileChildren(HqRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HqRoute: HqRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DevelopmentRoute: DevelopmentRoute,
  DonateRoute: DonateRoute,
  FaqRoute: FaqRoute,
  HqLoginRoute: HqLoginRoute,
  JoinRoute: JoinRoute,
  MissionRoute: MissionRoute,
  OperationsRoute: OperationsRoute,
  PartnersRoute: PartnersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SystemRoute: SystemRoute,
  TechnologyRoute: TechnologyRoute,
  WelcomeRoute: WelcomeRoute,
  WorkspacesRoute: WorkspacesRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  MeetingIdRoute: MeetingIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
